import Head from 'next/head'
import { Button, Heading, TextField, View } from "@aws-amplify/ui-react";
import { Inter } from '@next/font/google'
import { SyntheticEvent } from 'react';
import StandardCardCollection from '@/ui-components/StandardCardCollection';
import { DataStore } from 'aws-amplify';
import { Art } from '@/models';
const inter = Inter({ subsets: ['latin'] })


export default async function Home() {

  const generatePhoto(input: string, negativePrompt: string){
    const res = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ prompt: input, negative_prompt: negativePrompt })
    })

    let photo = await res.json();

    if (res.status !== 200) {
      console.log('error')
    } else {
      await DataStore.save(
        new Art({
          negative_prompt: negativePrompt,
          promt: input,
          timestamp: new Date().toISOString(),
          url: photo[0]
        })
      )
    }
  }





  const handleSubmit = (e: SyntheticEvent) => {
    e.preventDefault()
    const target = e.target as typeof e.target & {
      prompt: { value: string };
      negative_promt: { value: string }

    }

    if( target.prompt.value.trim() == "" ) return;

    generatePhoto(
      target.prompt.value.trim(),
      target.negative_promt.value.trim()
    );
    target.prompt.value = "",
    target.negative_promt.value = ""
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading level={1}> TEXT 2 IMAGE</Heading>

      <form onSubmit={handleSubmit}>

        <TextField label="Prompt"></TextField>
        <TextField label="Negative Prompt"></TextField>
        <Button type='submit' variation='primary'>Submit</Button>
      </form>

      <StandardCardCollection />
    </>
  )
}
