import Head from 'next/head'
import { Button, Heading, TextField, View } from "@aws-amplify/ui-react";
import { Inter } from '@next/font/google'
import { SyntheticEvent } from 'react';
import StandardCardCollection from '@/ui-components/StandardCardCollection';
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const handleSubmit = (e:SyntheticEvent) => {
    e.preventDefault()
    const target = event.target as typeof event.target & {
      prompt: {value: string};
      negative_promt:  {value: string}

    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading level={1}> TEXT 2 IMAGE</Heading>

      <form onSubmit={handleSubmit}>

      <TextField label="Prompt"></TextField>
      <TextField label="Negative Prompt"></TextField>
      <Button  type='submit' variation='primary'>Submit</Button>
      </form>

    <StandardCardCollection/>
    </>
  )
}
